# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b7a0739e5b9effe52fc9a2c3a82ce3bce64858c1c3352f609ed5b22b0b0b3eec6c1941bf46650e7638836748366cd345e9b4859f56083833f88d1ea49236d0e4

test:
  secret_key_base: 5e32fc9a74efebdd1b6dac9493bfff836e45c0d870780ac0c623b98beb3ce9c252c67070439fcb136e2ced94b3a0f57743d496908110fc3e41c02a15e7f45f37

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
